PR. Override application.properties
tempo92/SpringEdu pull request #15
Opened 2022-01-21 13:02 UTC by tempo92

2022-01-24 14:20 UTC, iv21dk commented
I don't undersand why you need to keep of this file: src/main/resources/application.local.properties.tmp

2022-01-24 14:38 UTC, iv21dk requested changes

2022-01-24 14:38 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/SpringEduApplication.java
> +    @PropertySource("classpath:application.properties"),
I cannot override `spring.data.mongodb.host` property

2022-01-26 07:32 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/SpringEduApplication.java
> +    @PropertySource("classpath:application.properties"),
fixed

2022-01-26 08:59 UTC, iv21dk approved these changes

2022-01-26 11:10 UTC, merged