PR. Add possibility to retrieve list of projects by pages (plus sorting)
tempo92/SpringEdu pull request #17
Opened 2022-01-24 13:20 UTC by tempo92

Closes #13 Closes #14

2022-01-24 14:55 UTC, iv21dk requested changes

2022-01-24 14:55 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/contoller/ProjectController.java
> +                required = true, defaultValue = "-1") Integer pageNumber
Why `required = true`. In fact the `pageNumber` and `pageSize` still optional

2022-01-24 14:55 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/service/ProjectService.java
> +        if (pageNumber < 0 ^ pageSize == 0) {
Only `null` is cosidered as no value.

2022-01-24 14:55 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/service/ProjectService.java
> +        if (substring != null && !substring.isEmpty()) {
I suggest to use MongoTemplate to build the request. Current implementation looks not so flexible.

2022-01-25 09:21 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/contoller/ProjectController.java
> +                required = true, defaultValue = "-1") Integer pageNumber
Fixed

2022-01-25 09:21 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/service/ProjectService.java
> +        if (pageNumber < 0 ^ pageSize == 0) {
Fixed

2022-01-26 11:12 UTC, merged