PR. SpringSecurity integration
tempo92/SpringEdu pull request #25
Opened 2022-01-31 17:36 UTC by tempo92

Closes #20

2022-02-01 12:28 UTC, iv21dk requested changes

2022-02-01 12:28 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/log/CustomLogger.java
> +                logger.info("Header: " + request.getHeader(headerNames.nextElement()));
This information would be more interesting in the request context. I suggest to add it as part of the first log message. You can use `StringBuilder` for it

2022-02-01 12:28 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/security/SecurityConfig.java
> +    private UserRepository userRepository;
It is better to avoid the bean injections in the configuration file. It is better to create them here. For example:
You can remove the `@Service` annotation from `CustomUserDetailsService` class and instead of this you can add the following method here:
```java
@Bean
public UserDetailsService customUserDetailsService(UserRepository userRepository) {
  return new CustomUserDetailsService(userRepository);
}
```

2022-02-01 12:28 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/security/SecurityConfig.java
> +        if (userRepository.findByUsername("user").isEmpty()){
In order to avoid bean injections to the configuration class it is beter to implement the logic in some service using `@PostConstruct` method. You can create a new service `UserService` or use the already existing `CustomUserDetailsService`.

2022-02-01 12:28 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/security/SecurityConfig.java
> +        if (userRepository.findByUsername("admin").isEmpty()){
The code is repeated several times. I suggest to extract them to new method like this:
```java
void createDefaultUserIfNeed(String username, String password, RoleName roleName)
```

2022-02-02 07:48 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/log/CustomLogger.java
> +                logger.info("Header: " + request.getHeader(headerNames.nextElement()));
Fixed

2022-02-02 07:48 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/security/SecurityConfig.java
> +    private UserRepository userRepository;
Fixed

2022-02-02 07:48 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/security/SecurityConfig.java
> +        if (userRepository.findByUsername("user").isEmpty()){
Fixed

2022-02-02 07:48 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/security/SecurityConfig.java
> +        if (userRepository.findByUsername("admin").isEmpty()){
Fixed

2022-02-03 08:07 UTC, iv21dk approved these changes

2022-02-03 11:40 UTC, merged