PR. Some restrictions for methods
tempo92/SpringEdu pull request #26
Opened 2022-01-31 20:40 UTC by tempo92

Closes #21

2022-02-01 12:35 UTC, iv21dk requested changes

2022-02-01 12:35 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/service/ProjectService.java
> +            throw new AccessDeniedException("Owner only");
Please try to resolve the issue using `@PreAuthorize` annotation and custom `PermissionEvaluator`

2022-02-01 12:35 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/service/ProjectService.java
> +    private String getUserId() {
Please try to use `@AuthenticationPrincipal` instead

2022-02-03 09:43 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/service/ProjectService.java
> +            throw new AccessDeniedException("Owner only");
Fixed

2022-02-03 09:43 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/service/ProjectService.java
> +    private String getUserId() {
Fixed

2022-02-07 06:50 UTC, iv21dk requested changes

2022-02-07 06:50 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/security/CustomPermissionEvaluator.java
> +    private final Logger logger = LogManager.getLogger(this.getClass());
You can use `@Log4j2` annotation instead. But in this case you will need to use `log` variable

2022-02-07 06:50 UTC, iv21dk commented on src/main/java/org/tempo/springEdu/security/CustomPermissionEvaluator.java
> +        logger.debug(
You can put your parameters using `{}` marker. So, the line can be like this:
```java
logger.debug("\nuserName: {}; userId: {}; projectId: {}", authentication.getName(), userId, projectId);
```

2022-02-07 06:50 UTC, iv21dk approved these changes

2022-02-07 17:53 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/security/CustomPermissionEvaluator.java
> +        logger.debug(
I`ll keep that in mind

2022-02-07 17:53 UTC, tempo92 commented on src/main/java/org/tempo/springEdu/security/CustomPermissionEvaluator.java
> +    private final Logger logger = LogManager.getLogger(this.getClass());
I'll keep that in mind

2022-02-07 17:55 UTC, merged